/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "backbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "onKeyboardButton", "rightImageWidth": 5, "text": "↺" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "upbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "↑" },
    "downbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "↓" },
    "fwdbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "▶▶" },
    "homebutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "home" },
    "infobutton": { "creationFunction": "CreateButton", "disabled": true, "leftImageWidth": 5, "onclick": "onKeyboardButton", "rightImageWidth": 5, "text": "info" },
    "infoswitch": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "keyboardbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "toggleKeyboard", "rightImageWidth": 5, "text": "⌨" },
    "leftbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "←" },
    "playbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "▶" },
    "rightbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "→" },
    "rokuipalert": { "creationFunction": "CreateIndicator", "criticalValue": 15, "onValue": 1, "warningValue": 10 },
    "rwdbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "◀◀" },
    "searchbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "onKeyboardButton", "rightImageWidth": 5, "text": "search" },
    "selectbutton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "buttonselect", "rightImageWidth": 5, "text": "okay" },
    "text": { "creationFunction": "CreateText", "text": "Roku IP" },
    "text1": { "creationFunction": "CreateText", "text": "Command Keys" },
    "text2": { "creationFunction": "CreateText", "text": "rewind" },
    "text3": { "creationFunction": "CreateText", "text": "home" },
    "text4": { "creationFunction": "CreateText", "text": "pause/play" },
    "text5": { "creationFunction": "CreateText", "text": "fast forward" },
    "text6": { "creationFunction": "CreateText", "text": "info" },
    "text7": { "creationFunction": "CreateText", "text": "back" },
    "text8": { "creationFunction": "CreateText", "text": "search" },
    "text9": { "creationFunction": "CreateText", "text": "keyboard mode" },
    "text10": { "creationFunction": "CreateText", "text": "space" }
};
